version: 2
jobs:
  build:
    docker:
      - image: djarek/boost_superproject_build
    parallelism: 2
    steps:
      - checkout
      - run: wget "https://raw.githubusercontent.com/boostorg/release-tools/develop/ci_boost_common.py" -P ${HOME}
      - run: wget "https://raw.githubusercontent.com/boostorg/release-tools/develop/ci_boost_release.py" -P ${HOME}
      - run: python ${HOME}/ci_boost_release.py checkout_post
      - run: python ${HOME}/ci_boost_release.py dependencies_override
      - run: EOL_A=(LF CRLF) EOL=${EOL_A[$CIRCLE_NODE_INDEX]} python ${HOME}/ci_boost_release.py test_override
