version: 2
jobs:
  build:
    docker:
      - image: djarek/boost_superproject_build
    parallelism: 2
    environment:
      EOL_N: LF CRLF
    steps:
      - checkout
      - run: wget "https://raw.githubusercontent.com/boostorg/release-tools/develop/ci_boost_common.py" -P ${HOME}
      - run: wget "https://raw.githubusercontent.com/boostorg/release-tools/develop/ci_boost_release.py" -P ${HOME}
      - run: ${HOME}/ci_boost_release.py checkout_post
      - run: ${HOME}/ci_boost_release.py dependencies_override
      - run: EOL_A=(${EOL_N}) EOL=${EOL_A[$CIRCLE_NODE_INDEX]} ${HOME}/ci_boost_release.py test_override
